### ISSUE TITLE
Unable to run on older operating systems?

### ISSUE THREAD

**Issue by parkerlreed** [Sibra-Soft/audiostation#1]
Windows XP 32bit.

I was able to install the program fully, associate a soundfont, and start Audiostation. It works until it throws some errors about WASAPI (Which only started appearing in Vista)

Is there no way to use this on a Windows XP system?

**Comment by alexxvandenberg** [comment]
Thanks for you bug report.
I will take a look at this issue, maybe I can implement a fix in the next version

**Comment by alexxvandenberg** [comment]
I found the problem, and why the application does not work on Windows XP.

In de latest released version (2.2) of the program this issue has not been fixed yet, I will release a new version (2.3) soon, in that version this issue will be fixed.

**Comment by anfyef** [comment]
Hi, waiting for the 2.3 version!
maybe possible run it on Windows 98 ?

**Comment by parkerlreed** [comment]
Hurrah! Thank you. 

It throws two warnings on startup but otherwise works fine. Playing some mp3 files great. 

    The procedure entry point _except_handler4_common could not be located in the dynamic link library msvcrt.dll

![20220406_142527](https://user-images.githubusercontent.com/841440/162043241-25b17f95-d6be-4826-9cfd-131c7c673a5e.jpg)
