### ISSUE TITLE
Some install/config issues and errors in drawings due font-scaling vs window scaling

### ISSUE THREAD

**Issue by codebeat-nl** [Sibra-Soft/audiostation#3]
Cool, I tried it. I can remember this was a Voyetra product? Made for Win3.11, 16 bits. Thanks for all the effort but..... there are some issues.

When you start the station for the first time it starts and shows an exception error. Second try it starts and hangs (desktop icons flickering) and I killed it via the taskmanager. Third try it starts and shows some draw issues.  This has something to do with font-scaling (standard 125% in Win7 and above), the window of the application does not support proportional scaling. This results in weird black window areas and drawings like time and such appear on the wrong location. The application window is also not resizable. 

The application itself works fine however because of the drawing issues it isn't pretty to look at.

Greetz,
Erwinus

**Comment by alexxvandenberg** [comment]
Thanks for you bug report. I will take a look at this issue, and try to fix this in the next version

**Comment by alexxvandenberg** [comment]
I have looked into this issue but it's hard to reproduce. Can you give me some more information like the OS you are running, screen resolution and maybe a screenshot?

**Comment by alexxvandenberg** [comment]
This ticket will be closed, if this issue stil needs to be resolved please open a new ticket in this Github repo
